use crate::TOKIO_RUNTIME;

use jni::objects::{GlobalRef, JClass, JObject, JString, JValue};
use jni::sys::jint;
use jni::{JNIEnv, JavaVM};
use librespot_core::authentication::Credentials;
use librespot_core::{Session, SessionConfig, SpotifyId, SpotifyUri};
use librespot_playback::{
    audio_backend::{AndroidSink, Sink},
    config::{AudioFormat, PlayerConfig},
    mixer::NoOpVolume,
    player::Player,
};
use log::{error, warn};
use once_cell::sync::OnceCell;
use std::sync::{Arc, Mutex};

static JAVA_VM: OnceCell<JavaVM> = OnceCell::new();
static PCM_CALLBACK: OnceCell<Mutex<Option<GlobalRef>>> = OnceCell::new();

/// Player related
static PLAYER: OnceCell<Arc<Player>> = OnceCell::new();
static SESSION: OnceCell<Session> = OnceCell::new();

/// Warning: Generated by Generative AI
/// The Rust-side trampoline called by AndroidSink (or other native code).
extern "C" fn rust_pcm_trampoline(
    data: *const u8,
    len: usize,
    sample_rate: u32,
    channels: u8,
    format: AudioFormat,
) {
    if data.is_null() || len == 0 {
        return;
    }

    // Get the GlobalRef to the Java callback
    let cb_mutex = match PCM_CALLBACK.get() {
        Some(m) => m,
        None => {
            warn!("PCM callback not registered (PCM_CALLBACK OnceCell empty)");
            return;
        }
    };

    let guard = match cb_mutex.lock() {
        Ok(g) => g,
        Err(e) => {
            warn!("PCM callback mutex poisoned: {e}");
            return;
        }
    };

    let cb_ref = match &*guard {
        Some(r) => r,
        None => {
            warn!("PCM callback is None");
            return;
        }
    };

    // Get the stored JavaVM
    let jvm = match JAVA_VM.get() {
        Some(j) => j,
        None => {
            warn!("JAVA_VM not set");
            return;
        }
    };

    // Attach current thread (daemon attach is fine for worker threads)
    let mut env = match jvm.attach_current_thread_as_daemon() {
        Ok(e) => e,
        Err(e) => {
            warn!("Failed to attach current thread to JVM: {e}");
            return;
        }
    };

    // Build byte slice from raw pointer
    let slice = unsafe { std::slice::from_raw_parts(data, len) };

    // Create Java byte[] (wrapper) from slice
    let jbyte_arr = match env.byte_array_from_slice(slice) {
        Ok(arr) => arr, // type: JByteArray / JPrimitiveArray<'_, i8>
        Err(e) => {
            warn!("Failed to create Java byte[]: {e}");
            return;
        }
    };

    // Convert to JObject so we can pass it as JValue::Object(&JObject)
    let jbuf_obj: JObject = JObject::from(jbyte_arr);

    // Call Java callback method:
    // void onNativePcm(byte[] data, int sampleRate, int channels, int format)
    let call_result = env.call_method(
        cb_ref.as_obj(),
        "onNativePcm",
        "([BIII)V",
        &[
            JValue::Object(&jbuf_obj),
            JValue::Int(sample_rate as jint),
            JValue::Int(channels as jint),
            JValue::Int(format as i32),
        ],
    );

    if let Err(e) = call_result {
        warn!("Calling Java onNativePcm failed: {e}");
    }

    // jbuf_obj is a local reference and will be cleaned up automatically
}

// This function initializes the playback session with users access token
#[unsafe(no_mangle)]
pub extern "system" fn Java_cc_tomko_outify_playback_AudioManager_initializeSession(
    mut env: JNIEnv,
    _this: JClass,
    access_token: JString,
    callback: JObject,
) {
    let token: String = match env.get_string(&access_token) {
        Ok(s) => s.into(),
        Err(e) => {
            log::error!("Failed to read access token from JNI: {e}");
            return;
        }
    };
    let callback_ref = env.new_global_ref(callback).unwrap();

    if SESSION.get().is_some() {
        log::warn!("Playback Session is already initialized!");
        return;
    }

    let rt = TOKIO_RUNTIME
        .get()
        .expect("Tokio runtime is not initialized!");

    log::info!("Initializing playback session..");

    let session_config = SessionConfig::default();
    let session = Session::with_handle(session_config, None, rt.handle().clone());

    log::info!("Playback session created!");

    if SESSION.set(session).is_err() {
        log::warn!("SESSION was concurrently set!");
        return;
    }

    let jvm = match env.get_java_vm() {
        Ok(j) => j,
        Err(e) => {
            log::error!("Failed to get JavaVM: {e}");
            return;
        }
    };

    let token_move = token.clone();
    log::info!("Auth token: {}", token_move);

    rt.spawn(async move {
        log::info!("Playback session connecting...");
        let credentials = Credentials::with_access_token(token_move);

        let session_ref = match SESSION.get() {
            Some(s) => s,
            None => {
                log::error!("SESSION disappeared before connect");
                return;
            }
        };

        let result = session_ref.connect(credentials, false).await;

        let mut env = match jvm.attach_current_thread() {
            Ok(e) => e,
            Err(e) => {
                log::error!("Failed to attach JavaVM: {e}");
                return;
            }
        };

        match result {
            Ok(_) => {
                log::info!("Playback session connected!");
                env.call_method(callback_ref.as_obj(), "onConnected", "()V", &[])
                    .expect("Failed to call 'onConnected'");
            }
            Err(e) => {
                log::error!("Session failed: {:?}", e);
                let msg = env
                    .new_string(e.to_string())
                    .expect("Failed to create error string");
                env.call_method(
                    callback_ref.as_obj(),
                    "onError",
                    "(Ljava/lang/String;)V",
                    &[JValue::Object(&msg)],
                )
                .expect("Failed to call 'onError'");
            }
        }
    });
}

// This function initializes the player and sink
// Make sure to initialize session first!
#[unsafe(no_mangle)]
pub extern "system" fn Java_cc_tomko_outify_playback_AudioManager_initializePlayer(
    env: JNIEnv,
    _this: JClass,
) {
    let audio_format = AudioFormat::S16;

    SESSION.get_or_init(|| {
        let session_config = SessionConfig::default();
        Session::new(session_config, None) // TODO: Implement cache
    });

    let sink_name = Some("android".to_string());
    let sink = librespot_playback::audio_backend::find(sink_name).unwrap();

    PLAYER.get_or_init(|| {
        let config = PlayerConfig::default();
        let session = SESSION.get().expect("Failed to retrieve playback Session!");
        Player::new(config, session.clone(), Box::new(NoOpVolume), move || {
            sink(None, audio_format)
        })
    });

    log::info!("Initialized player!");
}

// Temporary testing function for playing a track
#[unsafe(no_mangle)]
pub extern "system" fn Java_cc_tomko_outify_playback_AudioManager_playTrack(
    mut env: JNIEnv,
    _this: JClass,
    track_id: JString,
) {
    let track_id: String = env
        .get_string(&track_id)
        .expect("Failed to get JNI track_id!")
        .into();

    let track = SpotifyUri::Track {
        id: SpotifyId::from_base62(&track_id).unwrap(),
    };

    let player = PLAYER
        .get()
        .expect("Playback Player is not initialized! Cannot play a track");
    player.load(track, true, 0);

    log::info!("Playing a track {}", track_id);

    let rt = TOKIO_RUNTIME
        .get()
        .expect("Tokio runtime is not initialized!");

    rt.block_on(async { player.await_end_of_track().await })
}

/// JNI registration function — called from Java.
#[unsafe(no_mangle)]
pub extern "system" fn Java_cc_tomko_outify_playback_AudioManager_registerPcmCallback(
    env: JNIEnv,
    _class: JObject,
    callback: JObject,
) {
    match env.get_java_vm() {
        Ok(jvm) => {
            let _ = JAVA_VM.set(jvm);
        }
        Err(e) => {
            error!("Failed to get JavaVM in registerPcmCallback: {e}");
            return;
        }
    }

    let global_ref = match env.new_global_ref(callback) {
        Ok(g) => g,
        Err(e) => {
            error!("Failed to create GlobalRef for callback: {e}");
            return;
        }
    };

    PCM_CALLBACK.get_or_init(|| Mutex::new(None));
    if let Some(mutex) = PCM_CALLBACK.get() {
        match mutex.lock() {
            Ok(mut guard) => {
                *guard = Some(global_ref);
            }
            Err(e) => {
                error!("Failed to lock PCM_CALLBACK mutex: {e}");
                return;
            }
        }
    }

    AndroidSink::set_callback(rust_pcm_trampoline);
    log::info!("Registered PCM callback!");
}
